attempting to fix the run-scraper github action.

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -75,11 +75,20 @@ jobs:
       - name: Prepare config string
         id: prep
         run: |
-          CONFIG=$(jq -c . typesense-config.json)
-          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
+          if [ -f typesense-config.json ]; then
+            CONFIG=$(jq -c . typesense-config.json)
+            if [ -z "$CONFIG" ]; then
+              echo "typesense-config.json is empty or improperly formatted."
+              exit 1
+            fi
+            echo "CONFIG=$CONFIG" >> $GITHUB_ENV
+          else
+            echo "typesense-config.json file not found."
+            exit 1
+          fi
 
       - name: Run docsearch-scraper
         run: |
           docker run -i --env-file .env \
-            -e CONFIG="${{ env.CONFIG }}" \
+            -e CONFIG='${{ env.CONFIG }}' \
             typesense/docsearch-scraper:0.11.0
